name: Build and Upload Sphinx Docs

on:
  pull_request:
    branches:
      - main

jobs:
  build-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      # with:
      #   python-version: '3.8'

    - name: Setup Python environment
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --all-extras

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Build documentation
      run: |
        source .venv/bin/activate
        tox -e docs
        

    - name: Upload documentation artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: docs/build
 